[package]
name = "tokio-raw"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.83"
log = { version = "0.4", features = ["std", "serde"] }
simplelog = "0.11"
thiserror = "1.0.59"
serde_json = "1.0"
